[package]
name = "max11-colgen"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0"
flate2 = "1.1"
rayon = "1.11"
rustc-hash = "2.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
sha2 = "0.10"

[dev-dependencies]
tempfile = "3.20"

[profile.release]
lto = "thin"
codegen-units = 1
